// <auto-generated />
using CurriculoAutomatiza.Infraesctructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CurriculoAutomatiza.Infraesctructure.Migrations
{
    [DbContext(typeof(AutomatizaCurriculoDbContext))]
    partial class AutomatizaCurriculoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CurriculoAutomatiza.Domain.Entity.AreasInteresse", b =>
                {
                    b.Property<int>("AreasInteresseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ProfissionalId");

                    b.HasKey("AreasInteresseId");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("AreasInteresse");
                });

            modelBuilder.Entity("CurriculoAutomatiza.Domain.Entity.Profissional", b =>
                {
                    b.Property<int>("ProfissionalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(20)");

                    b.HasKey("ProfissionalId");

                    b.ToTable("Profissional");
                });

            modelBuilder.Entity("CurriculoAutomatiza.Domain.Entity.AreasInteresse", b =>
                {
                    b.HasOne("CurriculoAutomatiza.Domain.Entity.Profissional", "Profissional")
                        .WithMany("AreasInteresses")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
